# Generated by Django 5.1.2 on 2024-11-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
        migrations.RemoveField(
            model_name='location',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Plymouth', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='England', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(default='Devon', max_length=100),
        ),
        migrations.AddField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='route_type',
            field=models.CharField(choices=[('Out & Back', 'Out & Back'), ('Loop', 'Loop'), ('Point to Point', 'Point to Point')], default='Loop', max_length=15),
        ),
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], default='Moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
