SELECT 
    tc.TABLE_NAME, 
    kcu.COLUMN_NAME, 
    rc.CONSTRAINT_NAME, 
    rc.UNIQUE_CONSTRAINT_NAME
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu
ON 
    tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
JOIN 
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS rc
ON 
    tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE 
    tc.CONSTRAINT_TYPE = 'FOREIGN KEY';